settings:
  jira_project_key: "OPENG"
  status_mapping:
    opened: Untriaged
    closed: done
    not_planned: rejected
    
  components:
    - cos-lite
    - team-core
      
  add_gh_comment: false
  sync_description: false
  sync_comments: false

  label_mapping:
settings:
  jira_project_key: "OPENG"
  status_mapping:
    opened: Untriaged
    closed: done
    not_planned: rejected
    
  components:
    - catalogue
    - team-core
      
  add_gh_comment: false
  sync_description: false
  sync_comments: false

  label_mapping:
    "Type: Enhancement": Story