module.exports = {
    options: {
        devtools: false,
        duration: -1,
        failStatusCode: 1,
        fastForward: false,
        headless: true,
        loopCount: -1,
        sandbox: true,
        slowMo: false,
        verbose: true,
        watch: false,
    },
    paths: {
        workRoot: '.',
        testDataRoot: '.',
        testPathMatch: ['./*.ts'],
    },
    flood: {
        hosted: false,
        vu: 500,
        duration: 60,
        rampup: 0,
        regions: [''],
    },
    testSettings: {
        actionDelay: 1,
        blockDomains: [],
        browser: 'chromium',
        browserLaunchOptions: {},
        clearCache: true,
        clearCookies: true,
        consoleFilter: [],
        device: null,
        disableCache: true,
        extraHTTPHeaders: {},
        ignoreHTTPSErrors: false,
        incognito: true,
        launchArgs: [],
        responseTimeMeasurement: 'step',
        screenShotOnFailure: true,
        stages: [],
        stepDelay: 1,
        userAgent: '',
        viewport: { width: 1440, height: 900 },
        waitTimeout: '60s',
        waitUntil: false,
    }
}
