name: Test Suite
on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: python3 -m pip install tox
    - name: Run liters
      run: tox -vve lint
  integration-test-microk8s:
    name: Integration tests (microk8s)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup operator environment
      uses: charmed-kubernetes/actions-operator@master
      with:
        provider: microk8s
    - name: Run tests
      run: tox -e integration

